# Generated by Django 4.0.3 on 2022-04-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sub_iteam_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=25)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='sub_iteam',
            name='main_iteam',
        ),
        migrations.DeleteModel(
            name='Iteam',
        ),
        migrations.DeleteModel(
            name='Sub_Iteam',
        ),
    ]
