# Generated by Django 4.0.3 on 2022-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sub_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_item',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Items'),
        ),
    ]
