# Generated by Django 4.0.3 on 2022-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_book_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
