# Generated by Django 4.0.3 on 2022-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_book_amount_alter_book_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
