# Generated by Django 4.0.3 on 2022-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deli',
            field=models.BooleanField(default=False),
        ),
    ]
